<?php

/**
 * @file
 * Defines all the hooks this module implements.
 */

module_load_include('inc', 'islandora', 'includes/utilities');

$tesseract_required_version_number = '3.02.02';

// Determine if the server's operating system is Windows.
if (islandora_deployed_on_windows()) {
  // slangerx: For some reason, Tesseract 3.02.02 for Windows
  // identifies itself incorrectly: "tesseract -v" = "tesseract 3.02"
  // This hack makes it possible to still use OCR under Windows.
  $tesseract_required_version_number = '3.02';
}

// Constants.
define('ISLANDORA_OCR_TESSERACT_REQUIRED_VERSION', $tesseract_required_version_number);

/**
 * Implements hook_menu().
 */
function islandora_ocr_menu() {
  return array(
    'admin/islandora/ocr' => array(
      'title' => 'OCR Tool',
      'description' => 'Configure OCR generation.',
      'page callback' => 'drupal_get_form',
      'page arguments' => array('islandora_ocr_admin_settings_form'),
      'access arguments' => array('administer site configuration'),
      'file' => 'includes/admin.form.inc',
      'type' => MENU_NORMAL_ITEM,
    ),
  );
}
